spring:
  application:
    name: health-pal
  datasource:
    url: jdbc:postgresql://localhost:5432/health_pal_db
    username: postgres
    password: Jakarta39069!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        # format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
